### ISSUE TITLE
Save style to QML asks to choose a file not a folder

### ISSUE THREAD

**Issue by rodreras** [arc2qgis/qlyrx#11]
Hey! I just saw you updated the plugin so I ran to take a look. I think I found a little issue. 

When I click the option **Save Style to QML**, it opens a saving file window. It asks me to choose a  `.qml` file, not to save as this extension. See the printscreens below: 

Opening the plugin window: 

![Captura de tela de 2021-10-14 10-40-30](https://user-images.githubusercontent.com/53950449/137329232-906bf78d-aea2-4e34-a60f-9c9ead8323ba.png)

Browsing files: 

![Captura de tela de 2021-10-14 10-40-50](https://user-images.githubusercontent.com/53950449/137329229-0438d43e-3c80-47af-a05a-36c869e1d0ed.png)

Is that really supposed to happen or is it a bug?

**Comment by bogind** [comment]
Hi,
Yes, the intended behavior is indeed file selection and not folder selection.
We use the QGIS QgsFileWidget for this, but you should be able to enter the name of a new file.
What operating system are you using?
This seems like an issue with the file explorer QGIS is opening.

**Comment by rodreras** [comment]
I'm currently using Ubuntu 20.04 and QGIS 3.16.11.

Ok, @bogind I misunderstood I was supposed to put the name of a new file. Sorry for that.
 
I'd like to use this same space to better understand how the plugin works.

I have a `.lyrx` file with several symbols for lithological classification. 

After choosing the option "Load style from QML/SLD", it rises this error. 

![Captura de tela de 2021-10-17 13-11-11](https://user-images.githubusercontent.com/53950449/137635656-57a5f1ee-4b54-4791-a754-53e569ab58d1.png)

Python Version: 3.8.10 (default, Sep 28 2021, 16:10:42) [GCC 9.3.0] 
QGIS Version: 3.16.11-Hannover Hannover, 26cc1c762f 

This Python error might be because of my QML file or a problem in code?
