### ISSUE TITLE
Getting error when trying to use the tool

### ISSUE THREAD

**Issue by MottiMatete** [arc2qgis/qlyrx#19]
When trying to apply .lyrxsymbology to two different layers using the plugin qlyrx, I get the following error warnings:
![grafik](https://github.com/arc2qgis/qlyrx/assets/91371580/73d84bcc-1713-4062-b1aa-b1e3c6d2f5e6) Polygon feature
![grafik](https://github.com/arc2qgis/qlyrx/assets/91371580/7c7ccda7-789e-4d07-9819-84d4a5e1333f) Point feature.

**Comment by bogind** [comment]
fixed in v0.3.5
