### ISSUE TITLE
KeyError while using simple renderer LYRX

### ISSUE THREAD

**Issue by ZimmermannLfU** [arc2qgis/qlyrx#22]
While using a ShapeFile and referencing LYRX File I got this mistake:
_Ein Fehler trat bei der Ausführung von Python-Code auf: 
KeyError: 'fields' 
Traceback (most recent call last):
  File "C:\Users/XY/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qlyrx\qlyrx.py", line 328, in run
    self.j_data = self.read_lyrx(self.dlg.file_select.filePath())
  File "C:\Users/XY/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qlyrx\qlyrx.py", line 293, in read_lyrx
    self.styler.initial_lyrx_parse(data,layer)
  File "C:\Users/XY/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qlyrx\qlyrx_styler.py", line 425, in initial_lyrx_parse
    for f in renderers[z]['fields']:
KeyError: 'fields'
Python-Version: 3.9.18 (heads/master:5eba59e, Feb  1 2024, 20:02:10) [MSC v.1929 64 bit (AMD64)] 
QGIS-Version: 3.34.4-Prizren Prizren, decd43dc_

**Comment by ZimmermannLfU** [comment]
[example_simplerenderer.zip](https://github.com/user-attachments/files/17812940/example_simplerenderer.zip)

**Comment by ZimmermannLfU** [comment]
Here is an example for simple renderer in ArcGIS Pro. LYRX File contains a very simple symbology (grey thick outline).

**Comment by bogind** [comment]
We had some issues with this renderer type.
Which also caused some other unresolved issues with versions of QGIS above 3.28.
Fixed at [v0.3.5](https://github.com/arc2qgis/qlyrx/releases/tag/v0.3.5), it should be updated in the plugin repository soon as well, but for now you can follow the link to the releases page.
